publish:
  stage: publish
  extends: .common
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker load -i $CI_IMAGE:$CI_PIPELINE_ID.tar
    - VERSION=$(sh $SCRIPTS_DIR/get-version.sh)
    - docker push $CI_REGISTRY_IMAGE:$VERSION
    - if [[ $CI_COMMIT_REF_NAME == *"release/"* ]]; then docker push $CI_REGISTRY_IMAGE:latest; fi;
  only:
    - develop
    - /^release/